version: '3'

services:
  hazarder-apache:
    image: vladino.me:5000/vladinome:production
    container_name: vladinome_production
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
      - /etc/letsencrypt/archive/vladino.me:/etc/ssl/private
    command: /var/www/html/init-production.sh
    restart: always
    ports:
      - 443
    environment:
      - VIRTUAL_HOST=vladino.me
      - TZ=Europe/Vienna

networks:
  nginxdb_proxy:
    external: true
