version: '3'

services:
  hazarder-apache:
    image: registry.vladino.me:5000/vladinome:production
    container_name: vladinome_production
    networks:
      - nginxdb_proxy
    volumes:
      - .:/var/www/html
    command: /var/www/html/init-production.sh
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=www.vladino.me,vladino.me
      - TZ=Europe/Vienna

networks:
  nginxdb_proxy:
    external: true
