FROM php:7.2.4-apache

RUN a2enmod rewrite

RUN apt-get update

RUN apt-get install -y nano git curl libicu-dev libxml2-dev libgmp-dev zlib1g-dev libgpgme11-dev && \
    docker-php-ext-install \
    gmp \
    pdo_mysql \
    zip \
    intl

COPY docker/vhost /etc/apache2/sites-enabled/000-default.conf

COPY ./composer.json ./composer.phar /deploy/

WORKDIR /deploy
RUN php composer.phar install

WORKDIR /var/www/html